select * from dbo.Classified
select * from dbo.ClassifiedCharacteristics
select * from dbo.ClassifiedConstruction
select * from dbo.ClassifiedPurpose
select * from dbo.ClassifiedType
select * from dbo.EnergyClass
select * from dbo.ExteriorFeature
select * from dbo.FloorNo
select * from dbo.FloorType
select * from dbo.FrameType
select * from dbo.GoogleMapPlace
select * from dbo.HeatingSystem
select * from dbo.HeatingType
select * from dbo.InteriorFeature
select * from dbo.Photos
select * from dbo.PowerSupplyType
select * from dbo.SuitableFor
select * from dbo.AdvertiserInfo
select * from dbo.DbLogs